device: 'cuda'
lr: 1e-4
epochs: 200
data_dir: [
    "dataset/Honda-data/cityscapes-leftimg8bit-trainvaltest/",
    "dataset/Honda-data/nuimages/dark_cam_back",
    "dataset/Honda-data/nuimages/light_cam_back"
  ]
generated_version: '20240812_generated_data'
split_image: 'normal' # [grid_cell, random_crop, normal]

train:
  batch_size: 2
  num_workers: 8
  pin_memory: True
  pretrained_model: True
  image_size: 512
  eval_step: 1
  augmentation: False

valid:
  batch_size: 2
  num_workers: 4
  pin_memory: True
  image_size: 512
  augmentation: False

debug:
  tensorboard: exps/tensorboard
  weight: exps/weights/normal/best.pt
  prediction: exps/predictions/normal
  dataset_statistic: exps/dataset_statistic
  debug_idxs: [1, 2, 3, 4, 5]
  debug_ouput: exps/outputs